baseURL = "https://charlescsr.github.io/mlnotes/"
languageCode = "en-us"
title = "Charles CSR"
theme = "berbera"

pygmentsCodeFences=true
pygmentsUseClasses=true
canonifyURLs=true
publishDir="docs"
disableKinds = ["section", "taxonomy", "taxonomyTerm"]
